#lang scheme

;Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). 
;Are these processes iterative or recursive?

;TODO
; compute manually the procedure with the given arguments

(define (+ a b)
  (if (= a 0) 
      b 
      (inc (+ (dec a) b))))

(define (+ 4 5)
    (if (= 4 0) 
        5 
        (inc (+ (dec 4) 5)))) <--- calls the main procedure itself (8 + 1 = 9)
        
        > if(= 3 0 )
            5
            (inc (+ (dec 3) 5)) <--- calls the main procedure itself (7 + 1 = 8)
        
            > if(= 2 0)
                5
                (inc (+ (dec 2) 5)) <--- calls the main procedure itself (6 + 1 = 7)

                > if(= 1 0)
                    5
                    (inc (+ (dec 1) 5)) <--- calls the main procedure itself (6)
                
                    > if(= 0 0) 
                        5
                    6
                7
            8
        9    


;This procedure compiles via a recursive process, becuase the + inside the inc procedure, calls for the + procedure itself.
;In other words, the call for the + procedure is nested


;procedure 2
(define (+ a b)
  (if (= a 0) 
      b 
      (+ (dec a) (inc b))))

(define (+ 4 5)
    if( = 4 0)
     5
     (+ (dec 4) (inc 5))
)

; 4 is not equal to 0 so we run the else conditional expression
    (+ (dec 4) (inc 5))
    (+ 3 6)
    > 9 

;Both procedures compile to 9, the process being iterative. Each sub-procedure does not invoke the procedure itself nor does it go in a loop.
